### ISSUE TITLE
Crash on Build

### ISSUE THREAD

**Issue by Saifallak** [google/flutter-desktop-embedding#338]
Log
```
C:\Users\natsu\IdeaProjects\hi_world>flutter build windows -v
[  +22 ms] executing: [C:\SDKs\flutter\] git log -n 1 --pretty=format:%H
[  +72 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] 0545c63b9baca0d40c2126dba6366fad2b16d3c1
[   +3 ms] executing: [C:\SDKs\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +93 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.5.3-17-g0545c63b9
[  +11 ms] executing: [C:\SDKs\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[   +2 ms] executing: [C:\SDKs\flutter\] git ls-remote --get-url origin
[  +40 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +70 ms] executing: [C:\SDKs\flutter\] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] master
[  +40 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +14 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FuchsiaCacheArtifacts' is not required, skipping update.
[  +57 ms] Building Windows application...
[ +214 ms] #######################################################################
[   +2 ms] # Warning: Unable to find vcvars64.bat. Proceeding anyway; if it fails,
[   +1 ms] # run vcvars64.bat manually in this consolse then try again.
[        ] #######################################################################
[  +45 ms] Microsoft (R) Build Engine version 4.7.3190.0
[   +2 ms] [Microsoft .NET Framework, version 4.0.30319.42000]
[   +2 ms] Copyright (C) Microsoft Corporation. All rights reserved.
[   +1 ms] Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
[  +94 ms] Build started 20-Apr-19 4:52:09 PM.
[ +242 ms] Project "C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.sln" on node 1 (default targets).
[   +2 ms] ValidateSolutionConfiguration:
[        ]   Building solution configuration "Release|x64".
[  +66 ms] Project "C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.sln" (1) is building
"C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.vcxproj" (2) on node 1 (default targets).
[   +5 ms] C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.vcxproj(19,3): error MSB4019: The imported project
"C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that
the file exists on disk.
[   +2 ms] Done Building Project "C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.vcxproj" (default targets) --
FAILED.
[  +10 ms] Done Building Project "C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.sln" (default targets) -- FAILED.
[  +10 ms] Build FAILED.
[   +3 ms] "C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.sln" (default target) (1) ->
[   +1 ms] "C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.vcxproj" (default target) (2) ->
[   +1 ms]   C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.vcxproj(19,3): error MSB4019: The imported project
"C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that
the file exists on disk.
[   +2 ms]     0 Warning(s)
[        ]     1 Error(s)
[        ] Time Elapsed 00:00:00.34
[  +21 ms] Building Windows application... (completed in 0.7s)
[   +4 ms] "flutter windows" took 853ms.
[   +1 ms] "flutter windows" took 853ms.
Build process failed

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:42:5)
<asynchronous suspension>
#2      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:62:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:111:11)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#25     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#32     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#33     run (package:flutter_tools/runner.dart:51:10)
#34     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#35     main (file:///C:/SDKs/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

```

flutter doctor -v

```
C:\SDKs\flutter-desktop\example>flutter doctor -v
[√] Flutter (Channel master, v1.5.4-pre.17, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
    • Flutter version 1.5.4-pre.17 at C:\SDKs\flutter
    • Framework revision 0545c63b9b (15 hours ago), 2019-04-19 20:41:32 -0400
    • Engine revision ca31a7c57b
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 cf4444b803)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\SDKs\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
    • All Android licenses accepted.

[!] Android Studio (Version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.7019
    • Java Version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.7019

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.17763.437]

```

**Comment by stuartmorgan** [comment]
From your build output:
```
[ +214 ms] #######################################################################
[   +2 ms] # Warning: Unable to find vcvars64.bat. Proceeding anyway; if it fails,
[   +1 ms] # run vcvars64.bat manually in this consolse then try again.
[        ] #######################################################################
```

Did you manually run vcvars64.bat per that warning?

(Also, in the interests of improving auto-location of vcvars64, what is your Visual Studio installation path?)

**Comment by Saifallak** [comment]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE


that was the default location in the installer ^^

> Visual Studio 2019 Community

**Comment by Saifallak** [comment]
Also ,, vcvars64 wasn't working from CMD
```
C:\Users\natsu>vcvars64.bat
'vcvars64.bat' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by clarkezone** [comment]
Did you start a Visual Studio native tools cmd prompt or is that a regular cmd instance?  If the latter you need the former.

**Comment by Saifallak** [comment]
```
>vcvars64.bat
Command "vcvars64.bat" is not valid.
```

this is the output from VS

**Comment by stuartmorgan** [comment]
When you installed VS, did you include desktop development and C++ development support? That path should be one of the ones the script is looking for vcvars64.bat in, which makes me think you don't have it installed.

> C:\Users\natsu>vcvars64.bat
'vcvars64.bat' is not recognized as an internal or external command,
operable program or batch file.

Then you haven't added vcvars.bat to your path, as currently required by this project's build instructions:
https://github.com/google/flutter-desktop-embedding/tree/master/plugins#windows
(In your case the path would be 2019, not 2017. But I'm guessing you don't have it there, since the main build script didn't find it.)

**Comment by Saifallak** [comment]
okay solved,
anyway after i downloaded the C++ Dev support

i got this error:
```
[   +2 ms]   C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK
version 10.0.17134.0 was not found. Install the required version of Windows SDK or change the SDK version in the project
property pages or by right-clicking the solution and selecting "Retarget solution".
```

because my SDK is newer than the one you use (mine was : **10.0.17763.0**)
so also mention this in **Readme**

also those warning are normal ?
```
[ +130 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +30 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +21 ms] Artifact Instance of 'FuchsiaCacheArtifacts' is not required, skipping update.
```

**and in the end i got another error:**
```
[   +1 ms]   C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(378,5): error MSB8020: The build tools for
Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install
Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the
Project menu or right-click the solution, and then selecting "Retarget solution".
```

so i downloaded

>  **MSVC v141 - VS 2017 C++ x64/x86 build Tools (v14.16)** 

and finally it runs ,,

so from all that ,, 

- can you mention C++ Version in readme
- also can you mention that 2019 is not fully compatible

thanks in advance

**Comment by Saifallak** [comment]
example projects runs good now,
but when i create normal flutter project and move windows folder to there and try to run i get :
```
C:\Users\natsu\IdeaProjects\hi_world>flutter run -v
[  +21 ms] executing: [C:\SDKs\flutter\] git log -n 1 --pretty=format:%H
[  +58 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 0545c63b9baca0d40c2126dba6366fad2b16d3c1
[   +1 ms] executing: [C:\SDKs\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +70 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.5.3-17-g0545c63b9
[  +11 ms] executing: [C:\SDKs\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[        ] executing: [C:\SDKs\flutter\] git ls-remote --get-url origin
[  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +55 ms] executing: [C:\SDKs\flutter\] git rev-parse --abbrev-ref HEAD
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +179 ms] executing: C:\SDKs\android\platform-tools\adb.exe devices -l
[  +21 ms] Exit code 0 from: C:\SDKs\android\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +24 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FuchsiaCacheArtifacts' is not required, skipping update.
[ +132 ms] Launching lib/main.dart on Windows in debug mode...
[  +17 ms] Building Windows application...
[ +303 ms] **********************************************************************
[   +1 ms] ** Visual Studio 2019 Developer Command Prompt v16.0.2
[   +1 ms] ** Copyright (c) 2019 Microsoft Corporation
[        ] **********************************************************************
[ +954 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[  +69 ms] Microsoft (R) Build Engine version 16.0.461+g6ff56ef63c for .NET Framework
[   +1 ms] Copyright (C) Microsoft Corporation. All rights reserved.
[   +8 ms] Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
[ +157 ms] Build started 21-Apr-19 4:32:19 PM.
[ +509 ms] Project "C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.sln" on node 1 (default targets).
[   +3 ms] ValidateSolutionConfiguration:
[   +1 ms]   Building solution configuration "Debug|x64".
[ +564 ms] Project "C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.sln" (1) is building
"C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.vcxproj" (2) on node 1 (default targets).
[   +7 ms] InitializeBuildStatus:
[   +1 ms]   Touching
"C:\Users\natsu\IdeaProjects\hi_world\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbu
ild".
[   +1 ms] PreBuildEvent:
[   +1 ms]   Sync and build dependencies
[  +11 ms]   C:\Users\natsu\IdeaProjects\hi_world\windows\scripts\prepare_dependencies
"C:\Users\natsu\IdeaProjects\hi_world\windows\..\build\windows\intermediates\x64\Debug\Runner\"
[   +3 ms]   :VCEnd
[  +70 ms]   C:\Users\natsu\IdeaProjects\hi_world\windows\scripts\..\..\..\tools\sync_flutter_library
C:\Users\natsu\IdeaProjects\hi_world\windows\..\build\windows\intermediates\x64\Debug\Runner\flutter_library
[   +3 ms]   The system cannot find the path specified.
[   +7 ms] C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v150\Microsoft.CppCommon.targets(128,5): error MSB3073: The command
"C:\Users\natsu\IdeaProjects\hi_world\windows\scripts\prepare_dependencies
"C:\Users\natsu\IdeaProjects\hi_world\windows\..\build\windows\intermediates\x64\Debug\Runner\"
[C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.vcxproj]
[   +2 ms] C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v150\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" exited with
code 1. [C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.vcxproj]
[  +10 ms] Done Building Project "C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.vcxproj" (default targets) --
FAILED.
[  +24 ms] Done Building Project "C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.sln" (default targets) -- FAILED.
[  +38 ms] Build FAILED.
[   +6 ms] "C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.sln" (default target) (1) ->
[        ] "C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.vcxproj" (default target) (2) ->
[   +1 ms] (PreBuildEvent target) ->
[   +1 ms]   C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v150\Microsoft.CppCommon.targets(128,5): error MSB3073: The command
"C:\Users\natsu\IdeaProjects\hi_world\windows\scripts\prepare_dependencies
"C:\Users\natsu\IdeaProjects\hi_world\windows\..\build\windows\intermediates\x64\Debug\Runner\"
[C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.vcxproj]
[   +2 ms] C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v150\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" exited with
code 1. [C:\Users\natsu\IdeaProjects\hi_world\windows\Runner.vcxproj]
[   +3 ms]     0 Warning(s)
[   +1 ms]     1 Error(s)
[   +1 ms] Time Elapsed 00:00:01.26
[  +35 ms] Building Windows application... (completed in 2.8s)
[   +6 ms] "flutter run" took 3,204ms.
[   +1 ms] "flutter run" took 3,204ms.
Build process failed

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:42:5)
<asynchronous suspension>
#2      WindowsDevice.startApp (package:flutter_tools/src/windows/windows_device.dart:74:13)
<asynchronous suspension>
#3      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:364:54)
<asynchronous suspension>
#4      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:428:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#25     new Future.sync (dart:async/future.dart:224:31)
#26     CommandRunner.run (package:args/command_runner.dart:111:11)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#35     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#36     run (package:flutter_tools/runner.dart:51:10)
#37     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#38     main (file:///C:/SDKs/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#39     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by stuartmorgan** [comment]
Filed #342 for 2019 tracking, and updated the README to point to it.

> when i create normal flutter project and move windows folder to there

[The README](https://github.com/google/flutter-desktop-embedding/blob/master/Quick-Start.md#copy-the-linux-macos-andor-windows-directories) clearly indicates that just moving the folders isn't supported.

**Comment by pedromassango** [comment]
Someone can add the steps needed to successfully run this code in README.md? it is hard to get it working. Thank you

**Comment by stuartmorgan** [comment]
The READMEs are mostly exactly that, and have regularly been updated in response to specific issues. The example has also been simplified significantly, such that several of the things in this issue would no longer apply to the example.

Without knowing specifically what code you are trying to build and what issue you are having, I can't update the READMEs to help. If you file a new issue with details about what exactly you are trying to build and what isn't working I can help further.

**Comment by jablonskipj** [comment]
I am mostly using Fluter to develop on the Mac but the final application is ment to be used on Widnows. I wantes to build the version on the Windows 8.1 and I have the same issue as the one mentioned in the [comment](https://github.com/google/flutter-desktop-embedding/issues/338#issuecomment-485256488) but those problems appera for the master branch version of the `flutter-desktop-embedding`. I have tried to install the `MSVC v141 - VS 2017 C++ x64/x86 build Tools (v14.16)` instaed of `MSVC v142\ but this does not change anything. Do you know how to get rid of this problem?

**Comment by stuartmorgan** [comment]
@jablonskipj Please file a new bug, and include the full build logs. The comment you linked to wasn't actually ever related to this issue in the first place, and the specific thing that caused it in that case doesn't apply to master anyway, so whatever you are seeing should be investigated in a new issue.
