### ISSUE TITLE
No Hot reload and parse error

### ISSUE THREAD

**Issue by multiarts** [google/flutter-desktop-embedding#361]
Hello, I have tried to run the Flutter Desktop days without fail, the desktop emulator runs normal, but the hot reload does not work and loses connection "Exited (sigterm)" either in the terminal or in VS Code.
I've tried several Linux OSs and in no way succeeded.
The error message:

**Describe the bug**
```
Launching lib/main.dart on Linux in debug mode...
Error connecting to the service protocol: FormatException: Unexpected character (at character 293)
...ns":0,"avgCollectionPeriodMillis":0,000000,"used":524288,"capacity":2097...
                                       ^
Exited (sigterm)
```

**Development Environment (please complete the following information):**
* OS: Linux Debian 9
* Developer tools version (Xcode, Visual Studio, or gcc): 
GCC

**Doctor Output**
For build issues, please provide the output of `flutter doctor -v`:
```
[✓] Flutter (Channel master, v1.5.9-pre.69, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.5.9-pre.69 at /home/joao/dev/flutter
    • Framework revision 8e7c7fcbd4 (5 hours ago), 2019-04-30 06:30:38 -0400
    • Engine revision 64b1d38081
    • Dart version 2.3.0 (build 2.3.0-dev.0.3 c46deebfb6)

[!] Android toolchain - develop for Android devices
    ! Android SDK contains licenses only.
      Your first build of an Android application will take longer than usual, while gradle downloads the missing components. This functionality will only
      work if the licenses in the licenses folder in ANDROID_HOME are valid.
      If the Android SDK has been installed to another location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

      Certain features, such as `flutter emulators` and `flutter devices`, will not work without the currently missing SDK components.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.33.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.26.0

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

! Doctor found issues in 2 categories.
```

If the build is of anything other than `example`, please also provide the output of `tools/run_dart_tool doctor`:
```
Checking dependencies:

--------------------
Verifying git...
Running git --version
git version 2.11.0

--------------------
Verifying GN...
Running gn --version
Unhandled exception:
ProcessException: No such file or directory
  Command: gn --version
#0      runCommand (file:///home/joao/dev/flutter-desktop-embedding/tools/dart_tools/lib/run_command.dart:38:19)
<asynchronous suspension>
#1      verifyDependency (file:///home/joao/dev/flutter-desktop-embedding/tools/dart_tools/bin/doctor.dart:74:27)
<asynchronous suspension>
#2      main (file:///home/joao/dev/flutter-desktop-embedding/tools/dart_tools/bin/doctor.dart:57:16)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```
![image1](https://i.imgur.com/UQbJCCX.png)
![image2](https://i.imgur.com/A9ZnT17.png)

**Comment by stuartmorgan** [comment]
This is #356
