### ISSUE TITLE
Build Process Failed

### ISSUE THREAD

**Issue by Melvin-Abraham** [google/flutter-desktop-embedding#383]
I'm having trouble building the project in the `example` directory. Running `flutter run` in `cmd` provides me with a Build Exception...

**Note:** 
- The following issue might look similar to #338 but I am using _VS 2017_.
- I have installed Visual Studio in a _custom location_ (if this helps anyway).
- I have included `...\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build` in the PATH (User Environment Variables), so that it doesn't throw exceptions in case it fails to find `vcvars64.bat`.

## Logs

```
> flutter run

Launching lib/main.dart on Windows in debug mode...
Building Windows application...
Build process failed
```

***Verbose:***

```
> flutter run --verbose

[  +24 ms] executing: [E:\flutter\] git log -n 1 --pretty=format:%H
[  +77 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] a68f2963cdff2045424c664527177177340dcb70
[        ] executing: [E:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +73 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.5.8-261-ga68f2963c
[   +8 ms] executing: [E:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +49 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[   +1 ms] executing: [E:\flutter\] git ls-remote --get-url origin
[  +47 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +81 ms] executing: [E:\flutter\] git rev-parse --abbrev-ref HEAD
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] master
[  +47 ms] executing: E:\Android\sdk\platform-tools\adb.exe devices -l
[  +27 ms] Exit code 0 from: E:\Android\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
[  +26 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +10 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +126 ms] Launching lib/main.dart on Windows in debug mode...
[ +167 ms] Building Windows application...
[ +227 ms] **********************************************************************
[   +2 ms] ** Visual Studio 2017 Developer Command Prompt v15.9.6
[   +3 ms] ** Copyright (c) 2017 Microsoft Corporation
[        ] **********************************************************************
[+1501 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[ +177 ms] Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
[   +4 ms] Copyright (C) Microsoft Corporation. All rights reserved.
[  +27 ms] Build started 16-05-2019 01:59:08.
[ +129 ms] Project "E:\flutter-desktop-embedding\example\windows\Runner.vcxproj" on node 1 (default targets).
[   +3 ms] E:\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5):
error MSB8036: The Windows SDK version 10.0.17134.0 was not found. Install the required version of Windows SDK or change
the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
[E:\flutter-desktop-embedding\example\windows\Runner.vcxproj]
[   +5 ms] Done Building Project "E:\flutter-desktop-embedding\example\windows\Runner.vcxproj" (default targets) --
FAILED.
[   +2 ms] Build FAILED.
[   +3 ms] "E:\flutter-desktop-embedding\example\windows\Runner.vcxproj" (default target) (1) ->
[   +3 ms] (_CheckWindowsSDKInstalled target) ->
[   +1 ms]   E:\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.WindowsSDK.targets(46,5):
error MSB8036: The Windows SDK version 10.0.17134.0 was not found. Install the required version of Windows SDK or change
the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
[E:\flutter-desktop-embedding\example\windows\Runner.vcxproj]
[   +5 ms]     0 Warning(s)
[   +3 ms]     1 Error(s)
[        ] Time Elapsed 00:00:00.13
[   +8 ms] Building Windows application... (completed in 2.1s)
[   +4 ms] "flutter run" took 2,520ms.
[   +1 ms] "flutter run" took 2,520ms.
Build process failed

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:54:5)
<asynchronous suspension>
#2      WindowsDevice.startApp (package:flutter_tools/src/windows/windows_device.dart:77:13)
<asynchronous suspension>
#3      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:364:54)
<asynchronous suspension>
#4      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:430:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#13     Future._complete (dart:async/future_impl.dart:473:7)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#17     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#24     Future._complete (dart:async/future_impl.dart:473:7)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#26     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

---

**Development Environment:**
* ***OS***: Microsoft Windows 10 (Version 1809)
* ***Developer tools version***: Visual Studio 2017

**Doctor Output**

```
> flutter doctor -v

[√] Flutter (Channel master, v1.5.9-pre.261, on Microsoft Windows [Version 10.0.17763.475], locale en-IN)
    • Flutter version 1.5.9-pre.261 at E:\flutter
    • Framework revision a68f2963cd (77 minutes ago), 2019-05-15 15:25:39 -0400
    • Engine revision ce22829cd9
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 ea9b0cd0f5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\Android
    • Java binary at: E:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.2)
    • Android Studio at E:\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.17763.475]

! Doctor found issues in 1 category.
```

**Comment by stuartmorgan** [comment]
See https://github.com/google/flutter-desktop-embedding/issues/342#issuecomment-487810134

The real solution is to update the projects to use the new SDK (which I had actually planned on doing later today), but for now you can install the old one as described there. Closing as a dup.

**Comment by Melvin-Abraham** [comment]
Thanks. That worked for me...

**How to install a Windows SDK:**

[https://stackoverflow.com/questions/50590700/how-do-i-install-windows-10-sdk-for-use-with-visual-studio-2017](https://stackoverflow.com/questions/50590700/how-do-i-install-windows-10-sdk-for-use-with-visual-studio-2017)

**Comment by gotirahul96** [comment]
> See [#342 (comment)](https://github.com/google/flutter-desktop-embedding/issues/342#issuecomment-487810134)
> 
> The real solution is to update the projects to use the new SDK (which I had actually planned on doing later today), but for now you can install the old one as described there. Closing as a dup.

can you please elaborate you answer i'm new to flutter desktop.Thankyou.

**Comment by stuartmorgan** [comment]
@gotirahul96 This issue is nearly a year old, and nothing in it is relevant at this point. If you are having problems building after following all the instructions in the documentation, please file a new issue.
