### ISSUE TITLE
Example project - Build process failed - Windows

### ISSUE THREAD

**Issue by davystrong** [google/flutter-desktop-embedding#427]
**Describe the bug**
I'm trying to run the example project on Windows 10 but I get build process failed. I have tried all the available SDK versions in the Visual Studio 2019 installer without any luck.
Output from `flutter run -v`:
```
[  +68 ms] executing: [C:\Programs\flutter\] git log -n 1 --pretty=format:%H
[ +377 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +9 ms] d2e6ab69a26078303e8c8395ff569379104ec895
[   +2 ms] executing: [C:\Programs\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +787 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.7.2-45-gd2e6ab69a
[  +22 ms] executing: [C:\Programs\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +316 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\Programs\flutter\] git ls-remote --get-url origin
[ +503 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +373 ms] executing: [C:\Programs\flutter\] git rev-parse --abbrev-ref HEAD
[ +514 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +170 ms] executing: C:\Programs\android\platform-tools\adb.exe devices -l
[  +61 ms] Exit code 0 from: C:\Programs\android\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +83 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +32 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +518 ms] Launching lib/main.dart on Windows in debug mode...
[ +913 ms] Building Windows application...
[+1701 ms] **********************************************************************
[   +6 ms] ** Visual Studio 2019 Developer Command Prompt v16.1.2
[        ] ** Copyright (c) 2019 Microsoft Corporation
[        ] **********************************************************************
[+6536 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[ +359 ms] Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
[   +1 ms] Copyright (C) Microsoft Corporation. All rights reserved.
[  +19 ms] Building the projects in this solution one at a time. To enable parallel build, please add the
"-m" switch.
[ +366 ms] Build started 09/06/2019 10:29:34 PM.
[+1031 ms] Project
"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\Runner.sln"on node 1 (default targets).
[   +5 ms] ValidateSolutionConfiguration:
[   +1 ms]   Building solution configuration "Debug|x64".
[ +835 ms] Project
"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\Runner.sln"(1) is building
"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\Runner.vcxproj" (2) on node 1 (default targets).
[  +15 ms] InitializeBuildStatus:
[        ]   Touching
"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild".
[   +2 ms] PreBuildEvent:
[        ]   Sync and build dependencies
[  +26 ms]
"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\scripts\prepare_dependencies" debug
[   +3 ms]   :VCEnd
[+21162 ms] ClCompile:
[   +4 ms]   All outputs are up-to-date.
[ +194 ms] Link:
[   +4 ms]   C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE
/OUT:"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\..\build\windows\x64\Debug\Runner\Flutter Desktop Example.exe" /INCREMENTAL /NOLOGO
/LIBPATH:C:\Users\david\Documents\OpenCV\build\x64\vc14\lib flutter_windows.dll.lib opengl32.lib
opencv_world320d.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib
ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker'
uiAccess='false'" /manifest:embed /DEBUG:FASTLINK
/PDB:"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\..\build\windows\x64\Debug\Runner\Flutter Desktop Example.pdb" /TLBID:1 /DYNAMICBASE /NXCOMPAT
/IMPLIB:"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\..\build\windows\x64\Debug\Runner\Flutter Desktop Example.lib" /MACHINE:X64
"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\engine_method_result.obj"
[  +16 ms]
"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\flutter_window_controller.obj"
[   +3 ms]
"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\plugin_registrar.obj"
[   +6 ms]
"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\flutter_embedder_example.obj"
[+1083 ms] LINK : fatal error LNK1104: cannot open file 'opencv_world320d.lib'
[C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\Runner.vcxproj]
[ +117 ms] Done Building Project
"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\Runner.vcxproj" (default targets) -- FAILED.
[ +207 ms] Done Building Project
"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\Runner.sln"(default targets) -- FAILED.
[  +62 ms] Build FAILED.
[ +105 ms]
"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\Runner.sln"(default target) (1) ->
[  +35 ms]
"C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\Runner.vcxproj" (default target) (2) ->
[  +11 ms] (Link target) ->
[   +3 ms]   LINK : fatal error LNK1104: cannot open file 'opencv_world320d.lib'
[C:\Users\david\OneDrive\Documents\Programming\Flutter\flutter-desktop-embedding\example\windows\Runner.vcxproj]
[  +11 ms]     0 Warning(s)
[   +7 ms]     1 Error(s)
[   +6 ms] Time Elapsed 00:00:24.79
[  +45 ms] Building Windows application... (completed in 34.0s)
[  +56 ms] "flutter run" took 35,845ms.
[  +18 ms] "flutter run" took 35,845ms.
Build process failed

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:79:5)
<asynchronous suspension>
#2      WindowsDevice.startApp (package:flutter_tools/src/windows/windows_device.dart:77:13)
<asynchronous suspension>
#3      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:371:54)
<asynchronous suspension>
#4      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:461:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:424:33)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:415:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#25     new Future.sync (dart:async/future.dart:224:31)
#26     CommandRunner.run (package:args/command_runner.dart:112:14)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#35     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#36     run (package:flutter_tools/runner.dart:51:10)
#37     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#38     main (file:///C:/Programs/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#39     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Development Environment (please complete the following information):**
* OS: Windows 10
* Developer tools version (Xcode, Visual Studio, or gcc): Visual Studio 2019

**Doctor Output**
For build issues, please provide the output of `flutter doctor -v`:
```
[√] Flutter (Channel master, v1.7.3-pre.45, on Microsoft Windows [Version 10.0.17763.503], locale en-GB)
    • Flutter version 1.7.3-pre.45 at C:\Programs\flutter
    • Framework revision d2e6ab69a2 (3 days ago), 2019-06-07 07:48:27 +0100
    • Engine revision 0602dbb275
    • Dart version 2.3.2 (build 2.3.2-dev.0.1 6e0d978505)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Programs\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Programs\android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.1.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.1.29001.49

[!] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 15)
    • IntelliJ at C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 15.0.6
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
    X This install is older than the minimum recommended version of 2017.1.0.

[!] IntelliJ IDEA Community Edition (version 2017.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.34.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.0.2

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.17763.503]

! Doctor found issues in 3 categories.
```

**Comment by stuartmorgan** [comment]
You appear to have added settings for a completely unrelated project to your build:

> /LIBPATH:C:\Users\david\Documents\OpenCV\build\x64\vc14\lib
> [...]
> opencv_world320d.lib

If you didn't make these edits yourself in the project, you presumably have global overrides configured for Visual Studio from some other project which you'll need to remove.

**Comment by davystrong** [comment]
Ok, thanks, stupid mistake! I thought I was safe from that having installed VS from scratch but I must have been mistaken.
