### ISSUE TITLE
macOS build failed

### ISSUE THREAD

**Issue by enyo** [google/flutter-desktop-embedding#430]
**Describe the bug**

I checked out the repo on macOS, followed the instructions, and ran `flutter run` in `example/` and it failed:

```
$ flutter run
Launching lib/main.dart on macOS in debug mode...
** BUILD FAILED **

Building macOS application...
Build process failed
```

Running it again with `-v` showed that it was because it "could not find included file
'ephemeral/Flutter-Generated.xcconfig'"

(The full verbose log is at the end)

**Development Environment (please complete the following information):**
* OS: macOS Mojave 10.14.5

**Flutter verbose output**

```
$ flutter run -v
[  +33 ms] executing: [/Users/enyo/local/flutter/] git log -n 1 --pretty=format:%H
[  +52 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] bc7bc940836f1f834699625426795fd6f07c18ec
[        ] executing: [/Users/enyo/local/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +56 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.6.3-0-gbc7bc9408
[  +10 ms] executing: [/Users/enyo/local/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/enyo/local/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +49 ms] executing: [/Users/enyo/local/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[ +344 ms] Unable to locate an Android SDK.
[  +12 ms] Unable to locate an Android SDK.
[   +8 ms] executing: idevice_id -h
[  +42 ms] /usr/bin/xcrun simctl list --json devices
[ +286 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +175 ms] Launching lib/main.dart on macOS in debug mode...
[  +32 ms] Building macOS application...
[ +672 ms] User defaults from command line:
[        ]     IDEDerivedDataPathOverride = /Users/enyo/Develop/flutter-desktop-embedding/example/build/macos
[        ] Build settings from command line:
[   +1 ms]     OBJROOT = /Users/enyo/Develop/flutter-desktop-embedding/example/build/macos/Build/Intermediates.noindex
[        ]     SYMROOT = /Users/enyo/Develop/flutter-desktop-embedding/example/build/macos/Build/Products
[ +504 ms] note: Using new build system
[   +4 ms] note: Planning build
[  +69 ms] note: Using build description from disk
[        ] Build system information
[        ] error: /Users/enyo/Develop/flutter-desktop-embedding/example/macos/Configs/../Flutter/Flutter-Debug.xcconfig:1: could not find included file
'ephemeral/Flutter-Generated.xcconfig' in search paths (in target 'Build Flutter Bundle')
[   +5 ms] Build system information
[        ] error: /Users/enyo/Develop/flutter-desktop-embedding/example/macos/Configs/../Flutter/Flutter-Debug.xcconfig:1: could not find included file
'ephemeral/Flutter-Generated.xcconfig' in search paths (in target 'Build Flutter Bundle')
[        ] Build system information
[        ] error: /Users/enyo/Develop/flutter-desktop-embedding/example/macos/Configs/../Flutter/Flutter-Debug.xcconfig:1: could not find included file
'ephemeral/Flutter-Generated.xcconfig' in search paths (in target 'Build Flutter Bundle')
[        ] Build system information
[        ] error: /Users/enyo/Develop/flutter-desktop-embedding/example/macos/Configs/../Flutter/Flutter-Debug.xcconfig:1: could not find included file
'ephemeral/Flutter-Generated.xcconfig' in search paths (in target 'Runner')
[        ] Build system information
[        ] error: /Users/enyo/Develop/flutter-desktop-embedding/example/macos/Configs/../Flutter/Flutter-Debug.xcconfig:1: could not find included file
'ephemeral/Flutter-Generated.xcconfig' in search paths (in target 'Runner')
[        ] Build system information
[        ] error: /Users/enyo/Develop/flutter-desktop-embedding/example/macos/Configs/../Flutter/Flutter-Debug.xcconfig:1: could not find included file
'ephemeral/Flutter-Generated.xcconfig' in search paths (in target 'Runner')
[   +1 ms] ** BUILD FAILED **
[  +18 ms] Building macOS application... (completed in 1.3s)
[   +4 ms] "flutter run" took 2,190ms.
[        ] "flutter run" took 2,190ms.
Build process failed

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      buildMacOS (package:flutter_tools/src/macos/build_macos.dart:67:5)
<asynchronous suspension>
#2      MacOSDevice.startApp (package:flutter_tools/src/macos/macos_device.dart:78:13)
<asynchronous suspension>
#3      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:370:54)
<asynchronous suspension>
#4      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:430:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#13     Future._complete (dart:async/future_impl.dart:473:7)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#17     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#24     Future._complete (dart:async/future_impl.dart:473:7)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#26     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Doctor Output**
For build issues, please provide the output of `flutter doctor -v`:
```
$ flutter doctor -v
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale en-AT)
    • Flutter version 1.6.3 at /Users/enyo/local/flutter
    • Framework revision bc7bc94083 (3 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.35.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.14.5 18F132

! Doctor found issues in 2 categories.
```

**Comment by stuartmorgan** [comment]
> Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale en-AT)

Beta is too old; you need to be on master. See:
https://github.com/google/flutter-desktop-embedding/blob/master/README.md#setting-up

**Comment by enyo** [comment]
Oh man.. sorry, I thought that it was either beta or master for some reason. Read over it many times too. Thanks, will try again.
