### ISSUE TITLE
[MacOS/iOS plugins] MacOS plugins dependency breaks iOS cocoapod install

### ISSUE THREAD

**Issue by rxlabz** [google/flutter-desktop-embedding#440]
I try to use the same flutter project for both macOS and iOS.
All my platform specific code is separated in dedicated packages ( desktop and mobile ).
The desktop package uses the filechooser plugin, and has it declared in his pubspec. 
When I add the desktop_package as dependencies in the project pubspec, I can't compile the iOS app.
The filechooser plugin is added in the `.flutter-plugins` file and when cocoa pod run, I got this error  : 

```
12:46:48.587 27 info flutter.tools     Fetching external sources
12:46:48.587 28 info flutter.tools     -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
12:46:48.587 29 info flutter.tools     -> Fetching podspec for `file_chooser` from `.symlinks/plugins/file_chooser/ios`
12:46:48.587 30 info flutter.tools     [!] No podspec found for `file_chooser` in `.symlinks/plugins/file_chooser/ios`
```

The iOS app is compiled when I comment the desktop_package depency.

OS: iOS / MacOS
```
#flutter doctor
[✓] Flutter (Channel dev, v1.7.9, on Mac OS X 10.14.5 18F132, locale fr-FR)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] Connected device (3 available)
```

Complete cocoa pod log error :

```
12:46:43.869 1 info flutter.tools Launching lib/main.dart on iPhone 7 Plus in debug mode...
12:46:47.953 2 info flutter.tools Running pod install...
12:46:48.587 3 info flutter.tools CocoaPods' output:
12:46:48.587 4 info flutter.tools ↳
12:46:48.587 5 info flutter.tools     pod /Users/rxlabz/dev/tools/flutter
12:46:48.587 6 info flutter.tools     pod /Users/rxlabz/dev/labz/flutter/flutter-xplatform/xp_app
12:46:48.587 7 info flutter.tools     pod /Users/rxlabz/dev/labz/flutter/flutter-xplatform/xp_app/lib/main.dart
12:46:48.587 8 info flutter.tools     pod /Users/rxlabz/dev/labz/flutter/flutter-xplatform/xp_app/ios/Flutter/Generated.xcconfig/build
12:46:48.587 9 info flutter.tools     pod /Users/rxlabz/dev/labz/flutter/flutter-xplatform/xp_app/ios/Flutter/Generated.xcconfig/build/ios
12:46:48.587 10 info flutter.tools     pod /Users/rxlabz/dev/tools/flutter/bin/cache/artifacts/engine/ios
12:46:48.587 11 info flutter.tools     pod /Users/rxlabz/dev/labz/flutter/flutter-xplatform/xp_app/ios/Flutter/Generated.xcconfig/1.0.0
12:46:48.587 12 info flutter.tools     pod /Users/rxlabz/dev/labz/flutter/flutter-xplatform/xp_app/ios/Flutter/Generated.xcconfig/1
12:46:48.587 13 info flutter.tools     pod /Users/rxlabz/dev/labz/flutter/flutter-xplatform/flutter-desktop-embedding/plugins/file_chooser
12:46:48.587 14 info flutter.tools     pod /Users/rxlabz/.pub-cache/hosted/pub.dartlang.org/path_provider-1.1.0
12:46:48.587 15 info flutter.tools       Preparing
12:46:48.587 16 info flutter.tools 
12:46:48.587 17 info flutter.tools     Analyzing dependencies
12:46:48.587 18 info flutter.tools 
12:46:48.587 19 info flutter.tools     Inspecting targets to integrate
12:46:48.587 20 info flutter.tools       Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
12:46:48.587 21 info flutter.tools 
12:46:48.587 22 info flutter.tools     Finding Podfile changes
12:46:48.587 23 info flutter.tools       A file_chooser
12:46:48.587 24 info flutter.tools       - Flutter
12:46:48.587 25 info flutter.tools       - path_provider
12:46:48.587 26 info flutter.tools 
12:46:48.587 27 info flutter.tools     Fetching external sources
12:46:48.587 28 info flutter.tools     -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
12:46:48.587 29 info flutter.tools     -> Fetching podspec for `file_chooser` from `.symlinks/plugins/file_chooser/ios`
12:46:48.587 30 info flutter.tools     [!] No podspec found for `file_chooser` in `.symlinks/plugins/file_chooser/ios`
12:46:48.587 31 info flutter.tools 
12:46:48.587 32 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
12:46:48.587 33 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/user_interface.rb:86:in `titled_section'
12:46:48.587 34 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
12:46:48.587 35 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:854:in `fetch_external_source'
12:46:48.587 36 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:833:in `block (2 levels) in fetch_external_sources'
12:46:48.587 37 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:832:in `each'
12:46:48.587 38 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:832:in `block in fetch_external_sources'
12:46:48.587 39 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/user_interface.rb:64:in `section'
12:46:48.587 40 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:831:in `fetch_external_sources'
12:46:48.587 41 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:111:in `analyze'
12:46:48.587 42 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:398:in `analyze'
12:46:48.587 43 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
12:46:48.587 44 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/user_interface.rb:64:in `section'
12:46:48.588 45 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
12:46:48.588 46 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:156:in `install!'
12:46:48.588 47 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/command/install.rb:51:in `run'
12:46:48.588 48 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
12:46:48.588 49 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/lib/cocoapods/command.rb:52:in `run'
12:46:48.588 50 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/gems/cocoapods-1.7.2/bin/pod:55:in `<top (required)>'
12:46:48.588 51 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/bin/pod:22:in `load'
12:46:48.588 52 info flutter.tools     /usr/local/Cellar/cocoapods/1.7.2/libexec/bin/pod:22:in `<main>'
12:46:48.588 53 info flutter.tools 
12:46:48.588 54 info flutter.tools Error output from CocoaPods:
12:46:48.588 55 info flutter.tools ↳
12:46:48.588 56 info flutter.tools         [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
12:46:48.588 57 info flutter.tools         Consider adding the following to ~/.profile:
12:46:48.588 58 info flutter.tools 
12:46:48.588 59 info flutter.tools         export LANG=en_US.UTF-8
12:46:48.588 60 info flutter.tools         [0m
12:46:48.588 61 info flutter.tools 
12:46:48.615 62 info flutter.tools Error running pod install
12:46:48.615 63 info flutter.tools Error launching application on iPhone 7 Plus.
```

**Comment by stuartmorgan** [comment]
Currently Flutter assumes that a plugin supports both Android and iOS; this is covered by https://github.com/flutter/flutter/issues/10288 (and discussions are in progress about the details of a solution). Closing since the fix for the general problem is on the Flutter side, and tracked there.

Since these plugins are experimental and I don't expect them to continue as plugins in the medium-to-long term, working around it isn't a priority for the FDE project. That said, if you or someone else wants to contribute minimal "implementations" for the mobile platforms that don't do anything, but are enough to satisfy the `flutter` tool and compiler, I'm fine with landing them.
