### ISSUE TITLE
[macos] Build process failed without changing anything

### ISSUE THREAD

**Issue by jkmosa01** [google/flutter-desktop-embedding#555]
**Describe the bug**
I cloned the example folder and ran it in the macOS desktop environment. I closed the application, didn't change anything, and then tried to run it again, but the build failed. If I delete the repository and reclone it, the app runs fine, without changing anything else to my knowledge.

## command

flutter run -d macOS -v

## exception

FileSystemException: FileSystemException: Cannot resolve symbolic links, path = '/Users/me/Desktop/Developing/Flutter/flutter-desktop-embedding/example/macos/Flutter/ephemeral/FlutterMacOS.framework/FlutterMacOS' (OS Error: No such file or directory, errno = 2)
The following build commands failed:
	CompileSwift normal x86_64 /Users/me/Desktop/Developing/Flutter/flutter-desktop-embedding/example/macos/Flutter/GeneratedPluginRegistrant.swift
	CompileSwift normal x86_64 /Users/me/Desktop/Developing/Flutter/flutter-desktop-embedding/example/macos/MainFlutterWindow.swift
	CompileSwift normal x86_64 /Users/me/Desktop/Developing/Flutter/flutter-desktop-embedding/example/macos/AppDelegate.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(4 failures)
Finished with error: Build process failed

```
#0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:829:7)
#1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:395:5)
#2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:58:49)
#3      writeListIfChanged (package:flutter_tools/src/commands/assemble.dart:152:25)
#4      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:140:7)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _runZoned (dart:async/zone.dart:1516:10)
#11     runZoned (dart:async/zone.dart:1463:12)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#14     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#23     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#24     new Future.sync (dart:async/future.dart:224:31)
#25     CommandRunner.run (package:args/command_runner.dart:112:14)
#26     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#27     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1500:12)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1463:12)
#38     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#39     runInContext (package:flutter_tools/src/context_runner.dart:60:24)
<asynchronous suspension>
#40     run (package:flutter_tools/runner.dart:50:10)
#41     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#42     main (file:///Users/me/Desktop/Developing/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#43     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.10.2-pre.41, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.10.2-pre.41 at /Users/me/Desktop/Developing/Flutter/flutter
    • Framework revision 8eee93fa64 (3 hours ago), 2019-09-11 09:38:42 -0700
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/me/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/me/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/me/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Users/me/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270

[✓] Connected device (3 available)
    • macOS  • macOS  • darwin-x64     • Mac OS X 10.14.4 18E226
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by jkmosa01** [comment]
I am running on the latest version of flutter/flutter (master) and the latest version of this repository.

**Comment by stuartmorgan** [comment]
I saw this yesterday afternoon, but hadn't had time to investigate yet. It's definitely a recent regression. In the meantime `flutter clean` should be enough to work around it, rather than deleting the entire checkout.

**Comment by jonahwilliams** [comment]
I'm seeing something slightly different:

cp: cannot overwrite directory /Users/jonahwilliams/Documents/flutter-desktop-embedding/example/macos/Flutter/ephemeral/FlutterMacOS.framework/FlutterMacOS.framework/Resources with
non-directory /Users/jonahwilliams/Documents/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Resources

**Comment by stuartmorgan** [comment]
Relevant parts of the error log:
```
[ +149 ms] Target debug_unpack_macos failed: Exception: Failed to copy framework (exit 1:
[        ] ---
[        ] cp: cannot overwrite directory
```
```
build/Objects-normal/x86_64/MainFlutterWindow.o
[ +353 ms] [FDE path here]/example/macos/MainFlutterWindow.swift:16:8: error: no such
module 'FlutterMacOS'
[        ] import FlutterMacOS
```
