### ISSUE TITLE
Building Windows process failed

### ISSUE THREAD

**Issue by bahadurvaibhav** [google/flutter-desktop-embedding#611]
**System info**
windows 10 home
visual studio Community 2019 16.3.10
Desktop development with C++
MSVC v142 installed
Windows 10 SDK (10.0.18362.0 and 10.0.17763.0) installed

`C:\flutter\bin\flutter run -d windows -v`
```
[  +19 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +62 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 4c64b715d9a677922ef02f2643211a6282926eb5
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +57 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.7-17-g4c64b715d
[   +6 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +67 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[  +81 ms] executing: C:\Users\bahad\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +26 ms] Exit code 0 from: C:\Users\bahad\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +13 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +30 ms] Found plugin esys_flutter_share at C:\flutter\.pub-cache\hosted\pub.dartlang.org\esys_flutter_share-1.0.2\
[  +17 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.4.4\
[   +2 ms] Found plugin permission_handler at C:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-4.0.0\
[   +6 ms] Found plugin sqflite at C:\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.1.7+2\
[   +8 ms] Found plugin video_player at C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.2+5\
[   +2 ms] Found plugin webview_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.15+1\
[  +32 ms] Found plugin esys_flutter_share at C:\flutter\.pub-cache\hosted\pub.dartlang.org\esys_flutter_share-1.0.2\
[   +9 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.4.4\
[   +1 ms] Found plugin permission_handler at C:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-4.0.0\
[   +4 ms] Found plugin sqflite at C:\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.1.7+2\
[   +6 ms] Found plugin video_player at C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.2+5\
[   +1 ms] Found plugin webview_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.15+1\
[  +33 ms] Generating C:\Apps\practice\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +63 ms] Launching lib\main.dart on Windows in debug mode...
[  +17 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest
-requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.Windows10SDK.17763
[  +29 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8
-latest -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.Windows10SDK.17763
[        ] [
             {
               "instanceId": "4b5a0dec",
               "installDate": "2019-11-22T08:05:10Z",
               "installationName": "VisualStudio/16.3.10+29519.87",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.3.29519.87",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.3.10",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2019-11-22T08:05:10.8731238Z",
               "catalog": {
                 "buildBranch": "d16.3",
                 "buildVersion": "16.3.29519.87",
                 "id": "VisualStudio/16.3.10+29519.87",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.3.10",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "10",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.3.10+29519.87",
                 "requiredEngineVersion": "2.3.2283.19382"
               },
               "properties": {
                 "campaignId": "1440029644.1574409598",
                 "channelManifestId": "VisualStudio.16.Release/16.3.10+29519.87",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual
                 Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[   +5 ms] Building Windows application...
[   +1 ms] executing: [C:\Apps\practice\windows\] C:\flutter\packages\flutter_tools\bin\vs_build.bat C:\Program Files
(x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat Runner.sln Debug
[ +189 ms] **********************************************************************
[   +2 ms] ** Visual Studio 2019 Developer Command Prompt v16.3.10
[        ] ** Copyright (c) 2019 Microsoft Corporation
[   +1 ms] **********************************************************************
[+2869 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[  +79 ms] Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Framework
[   +1 ms] Copyright (C) Microsoft Corporation. All rights reserved.
[        ] MSBUILD : error MSB1009: Project file does not exist.
[        ] Switch: Runner.sln
[+1107 ms] Building Windows application... (completed in 4.2s)
[   +2 ms] "flutter run" took 4,717ms.
Build process failed. To view the stack trace, please run `flutter run -d windows -v`.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:82:5)
<asynchronous suspension>
#2      WindowsDevice.buildForDevice (package:flutter_tools/src/windows/windows_device.dart:46:11)
#3      DesktopDevice.startApp (package:flutter_tools/src/desktop_device.dart:87:13)
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:448:54)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:266:39)
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:499:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#9      _rootRunUnary (dart:async/zone.dart:1134:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#17     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#19     _rootRunUnary (dart:async/zone.dart:1134:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#24     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#25     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#26     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#27     IosProject.isSwift (package:flutter_tools/src/project.dart)
#28     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#29     _rootRunUnary (dart:async/zone.dart:1134:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#34     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#35     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#36     _rootRun (dart:async/zone.dart:1126:13)
#37     _CustomZone.run (dart:async/zone.dart:1023:19)
#38     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#39     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#42     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

`flutter doctor -v`
[√] Flutter (Channel master, v1.12.8-pre.17, on Microsoft Windows [Version 10.0.18362.476], locale en-SG)
    • Flutter version 1.12.8-pre.17 at C:\flutter
    • Framework revision 4c64b715d9 (3 hours ago), 2019-11-21 22:12:24 -0800
    • Engine revision 7e68097cc1
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\bahad\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.3.10)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.3.29519.87

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.18362.476]

! Doctor found issues in 1 category.

**Comment by stuartmorgan** [comment]
> MSBUILD : error MSB1009: Project file does not exist

You don't appear to have added Windows support to your project. Please read the README instructions for setting up your own project to run on Windows.
