### ISSUE TITLE
Flutter Plugin Example 'lib/main.dart not found"

### ISSUE THREAD

**Issue by Nailik** [google/flutter-desktop-embedding#623]
Hi,
i'm building an addon, the Android and the Web part are Working.
I added desktop support to the example (the example that's created with the plugin) to test if i can add desktop support to my plugin.
So the example is running on the desktop, but when i add the windows section

```plugin:
platforms:
      android:
        package: de.kilianeller.plugin_example
        pluginClass: PluginExample
      web:
        pluginClass: PluginExampleWeb
        fileName: web/plugin_example_web.dart
        # when i enable windows in plugin, then example is not running anymore
      windows:
        pluginClass: PluginExample
```

Then it's not building and the important line after `plugin_example\example>flutter run -d windows -v` is probably 

```
...\plugin_example\example\windows\flutter\generated_plugin_registrant.cc(7,10): 
fatal error C1083: Datei (Include) kann nicht geöffnet werden: "flutter_usb.h": 
No such file or directory [...\plugin_example\example\windows\Runner.vcxproj]
```

So it somehow seems like not the plugin is building it's windows part but the example (which should only use the plugin like any other dart file) ......

The full code is in this project [https://github.com/Nailik/flutter_usb/tree/c2bfcfd3bfc0dce191cdd716f6da0af7dcb4bcc2](url) 
(It's named FlutterUsb but basically it's just the example plugin on the windows side)

I hope it's understandable and someone can point out my issue.

**Comment by stuartmorgan** [comment]
It's not working because you haven't followed [the instructions for adding a plugin](https://github.com/google/flutter-desktop-embedding/blob/master/plugins/README.md#windows) in your example app.

**Comment by Nailik** [comment]
Yes, that was the Problem, i missed some steps there - thank you very much.

**Comment by Nailik** [comment]
I have seen that `flutter create .` now also supports windows desktop. I tried it, and this error 
`Target file "lib\main.dart" not found.` occurs again when i add `windows:  pluginClass: FlutterPlugin` to my `pubspec.yaml`.
I just created a new Project to test flutter create.
Created Project, used flutter config --enable-windows-desktop, used flutter create . to create folders for windows stuff, added `windows:  pluginClass: FlutterPlugin` to my `pubspec.yaml`.

>flutter run -d windows -v
shows following:

```
flutter run -d windows -v
[  +17 ms] executing: [C:\Flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +65 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 1118d24794088119bbd649462e320d246533001e
[        ] executing: [C:\Flutter/] git describe --match *.*.* --first-parent --long --tags
[  +70 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.18.0-dev.4.0-94-g1118d24794
[   +7 ms] executing: [C:\Flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\Flutter/] git ls-remote --get-url origin
[  +41 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +75 ms] executing: [C:\Flutter/] git rev-parse --abbrev-ref HEAD
[  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +55 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +14 ms] executing: C:\Users\kilia\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +43 ms] List of devices attached
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +17 ms] "flutter run" took 104ms.
Target file "lib\main.dart" not found.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:832:9)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:332:19)
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:711:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:628:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:618:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:340:21)
#14     _rootRunUnary (dart:async/zone.dart:1192:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
#22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
#23     _rootRunUnary (dart:async/zone.dart:1192:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#28     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#29     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#30     _rootRun (dart:async/zone.dart:1184:13)
#31     _CustomZone.run (dart:async/zone.dart:1077:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Comment by stuartmorgan** [comment]
If you have an issue with `flutter create` you should file a Flutter issue. The `flutter` tool is not part of this repository.

**Comment by Nailik** [comment]
okay, i created another plain project and it worked for no reason
