### ISSUE TITLE
Running failed example windows

### ISSUE THREAD

**Issue by Ali1Ammar** [google/flutter-desktop-embedding#626]
Hi
I have problem after last upgrade flutter 1.13.6-pre.40
when run example app or any app on windows 10
 I get this error 

I try : 
      update flutter flutter-desktop-embedding and example to last version
      run flutter precache --windows
      run flutter clean

 ```

D:\fvm\desktop_app\example>flutter run -d windows -v
[  +19 ms] executing: [D:\fvm\master\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +57 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 43a8c2434494274a42631a56ae54867e579cde5e
[        ] executing: [D:\fvm\master\] git describe --match v*.*.* --first-parent --long --tags
[  +59 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.13.5-40-g43a8c2434
[   +6 ms] executing: [D:\fvm\master\] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [D:\fvm\master\] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +66 ms] executing: [D:\fvm\master\] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +32 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +159 ms] executing: D:\android\sdk\platform-tools\adb.exe devices -l
[  +21 ms] Exit code 0 from: D:\android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +12 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +165 ms] Launching lib\main.dart on Windows in debug mode...
[  +26 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.Windows10SDK.17763
[  +25 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.Windows10SDK.17763
[   +1 ms] [
             {
               "instanceId": "4fb834e7",
               "installDate": "2019-12-02T23:09:25Z",
               "installationName": "VisualStudio/16.3.10+29519.87",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.3.29519.87",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.3.10",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2019-12-02T23:09:25.0605462Z",
               "catalog": {
                 "buildBranch": "d16.3",
                 "buildVersion": "16.3.29519.87",
                 "id": "VisualStudio/16.3.10+29519.87",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.3.10",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "10",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.3.10+29519.87",
                 "requiredEngineVersion": "2.3.2283.19382"
               },
               "properties": {
                 "campaignId": "1346216582.1575322022",
                 "channelManifestId": "VisualStudio.16.Release/16.3.10+29519.87",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[   +4 ms] Building Windows application...
[   +1 ms] executing: [D:\fvm\desktop_app\example\windows\] D:\fvm\master\packages\flutter_tools\bin\vs_build.bat C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat Runner.sln Debug
[ +186 ms] **********************************************************************
[   +3 ms] ** Visual Studio 2019 Developer Command Prompt v16.3.10
[  +10 ms] ** Copyright (c) 2019 Microsoft Corporation
[        ] **********************************************************************
[+2200 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[  +76 ms] Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Framework
[   +4 ms] Copyright (C) Microsoft Corporation. All rights reserved.
[   +7 ms] Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
[  +32 ms] Build started 12/30/2019 7:37:06 PM.
[ +116 ms] Project "D:\fvm\desktop_app\example\windows\Runner.sln" on node 1 (default targets).
[   +3 ms] ValidateSolutionConfiguration:
[   +8 ms]   Building solution configuration "Debug|x64".
[ +158 ms] Project "D:\fvm\desktop_app\example\windows\Runner.sln" (1) is building "D:\fvm\desktop_app\example\windows\Runner.vcxproj.metaproj" (2) on node 1 (default targets).
[   +5 ms] Project "D:\fvm\desktop_app\example\windows\Runner.vcxproj.metaproj" (2) is building "D:\fvm\desktop_app\example\windows\FlutterBuild.vcxproj" (3) on node 1 (default targets).
[   +7 ms] InitializeBuildStatus:
[   +2 ms]   Touching "x64\Debug\Flutter Build.tlog\unsuccessfulbuild".
[  +11 ms] CustomBuildStep:
[        ]   Running Flutter backend build
[  +12 ms]   "D:\fvm\desktop_app\example\windows\scripts\prepare_dependencies" Debug
[   +1 ms]   :VCEnd
[ +213 ms] ../../../master/packages/flutter_tools/bin/tool_backend.dart(6,8): error GBB7C8005: Error when reading '../../../master%20-%20Copy/.pub-cache/hosted/pub.dartlang.org/path-1.6.4/lib/path.dart': The system cannot find the path
specified. [D:\fvm\desktop_app\example\windows\FlutterBuild.vcxproj]
[   +3 ms]   import 'package:path/path.dart' as path; // ignore: package_path_import.
[   +7 ms]          ^
[   +9 ms] ../../../master/packages/flutter_tools/bin/tool_backend.dart(16,74): error GB1B8BC88: Method not found: 'join'. [D:\fvm\desktop_app\example\windows\FlutterBuild.vcxproj]
[        ]     final String flutterTarget = Platform.environment['FLUTTER_TARGET'] ?? path.join('lib', 'main.dart');
[   +1 ms]                                                                            ^^^^
[        ] ../../../master/packages/flutter_tools/bin/tool_backend.dart(35,36): error GB1B8BC88: Method not found: 'join'. [D:\fvm\desktop_app\example\windows\FlutterBuild.vcxproj]
[   +2 ms]     final String flutterExecutable = path.join(
[   +6 ms]                                      ^^^^
[   +2 ms] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(271,5): error MSB3073: The command ""D:\fvm\desktop_app\example\windows\scripts\prepare_dependencies" Debug
[D:\fvm\desktop_app\example\windows\FlutterBuild.vcxproj]
[   +1 ms] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(271,5): error MSB3073: :VCEnd" exited with code 254. [D:\fvm\desktop_app\example\windows\FlutterBuild.vcxproj]
[   +6 ms] Done Building Project "D:\fvm\desktop_app\example\windows\FlutterBuild.vcxproj" (default targets) -- FAILED.
[   +8 ms] Done Building Project "D:\fvm\desktop_app\example\windows\Runner.vcxproj.metaproj" (default targets) -- FAILED.
[        ] Done Building Project "D:\fvm\desktop_app\example\windows\Runner.sln" (default targets) -- FAILED.
[   +2 ms] Build FAILED.
[   +7 ms] "D:\fvm\desktop_app\example\windows\Runner.sln" (default target) (1) ->
[   +2 ms] "D:\fvm\desktop_app\example\windows\Runner.vcxproj.metaproj" (default target) (2) ->
[   +8 ms] "D:\fvm\desktop_app\example\windows\FlutterBuild.vcxproj" (default target) (3) ->
[   +3 ms] (CustomBuildStep target) ->
[  +10 ms]   ../../../master/packages/flutter_tools/bin/tool_backend.dart(6,8): error GBB7C8005: Error when reading '../../../master%20-%20Copy/.pub-cache/hosted/pub.dartlang.org/path-1.6.4/lib/path.dart': The system cannot find the path
specified. [D:\fvm\desktop_app\example\windows\FlutterBuild.vcxproj]
[   +1 ms]   ../../../master/packages/flutter_tools/bin/tool_backend.dart(16,74): error GB1B8BC88: Method not found: 'join'. [D:\fvm\desktop_app\example\windows\FlutterBuild.vcxproj]
[   +9 ms]   ../../../master/packages/flutter_tools/bin/tool_backend.dart(35,36): error GB1B8BC88: Method not found: 'join'. [D:\fvm\desktop_app\example\windows\FlutterBuild.vcxproj]
[   +1 ms]   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(271,5): error MSB3073: The command ""D:\fvm\desktop_app\example\windows\scripts\prepare_dependencies" Debug
[D:\fvm\desktop_app\example\windows\FlutterBuild.vcxproj]
[   +6 ms] C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(271,5): error MSB3073: :VCEnd" exited with code 254. [D:\fvm\desktop_app\example\windows\FlutterBuild.vcxproj]
[   +4 ms]     0 Warning(s)
[  +11 ms]     4 Error(s)
[   +2 ms] Time Elapsed 00:00:00.57
[+1321 ms] Building Windows application... (completed in 4.5s)
[   +4 ms] "flutter run" took 5,022ms.`


 `Build process failed. To view the stack trace, please run flutter run -d windows -v.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:82:5)
<asynchronous suspension>
#2      WindowsDevice.buildForDevice (package:flutter_tools/src/windows/windows_device.dart:46:11)
#3      DesktopDevice.startApp (package:flutter_tools/src/desktop_device.dart:87:13)
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:430:54)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:334:39)
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:555:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#9      _rootRunUnary (dart:async/zone.dart:1134:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#17     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#19     _rootRunUnary (dart:async/zone.dart:1134:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#24     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#25     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)`

```
______________________________________________________

flutter doctor

```
[√] Flutter (Channel master, v1.13.6-pre.40, on Microsoft Windows [Version 10.0.18363.535], locale en-US)
    • Flutter version 1.13.6-pre.40 at D:\fvm\master
    • Framework revision 43a8c24344 (20 hours ago), 2019-12-29 12:28:57 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\android\sdk
    • Java binary at: D:\program\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.3.10)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.3.29519.87

[√] Android Studio (version 3.5)
    • Android Studio at D:\program\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.535]
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by Ali1Ammar** [comment]
when i  return to  v1.13.1-pre.99,
work fine

```
[√] Flutter (Channel master, v1.13.1-pre.99, on Microsoft Windows [Version 10.0.18363.535], locale en-US)
    • Flutter version 1.13.1-pre.99 at D:\fvm\master
    • Framework revision 354f80b84a (3 weeks ago), 2019-12-11 16:36:03 -0800
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\android\sdk
    • Java binary at: D:\program\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.3.10)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.3.29519.87

[√] Android Studio (version 3.5)
    • Android Studio at D:\program\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.535]
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by stuartmorgan** [comment]
```
[ +213 ms] ../../../master/packages/flutter_tools/bin/tool_backend.dart(6,8): error GBB7C8005: Error when reading '../../../master%20-%20Copy/.pub-cache/hosted/pub.dartlang.org/path-1.6.4/lib/path.dart': The system cannot find the path
specified. [D:\fvm\desktop_app\example\windows\FlutterBuild.vcxproj]
[   +3 ms]   import 'package:path/path.dart' as path; // ignore: package_path_import.
[   +7 ms]          ^
```

This error is coming from `flutter_tools`, not code that's part of the flutter-desktop-embedding repository. Given that `master%20-%20Copy` is an unusual path component, and doesn't match your `flutter doctor` output, my guess is that you've moved your Flutter installation after running it in a way that's confused the `flutter` tool, but if you believe it's a bug rather than a local configuration error you'll need to file it in the [Flutter repository](https://github.com/flutter/flutter/issues).
