### ISSUE TITLE
Windows build failure with path_provider_fde

### ISSUE THREAD

**Issue by gotirahul96** [google/flutter-desktop-embedding#676]
After running flutter run -d windows -v
```
[  +25 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +143 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] d3387bc916da209506db3f07976208bb2f81f911
[        ] executing: [C:\flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +111 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.15.3-81-gd3387bc91
[  +10 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +70 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +62 ms] Exit code 0 from: git ls-remote --get-url origin
[   +5 ms] https://github.com/flutter/flutter.git
[ +117 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +77 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[  +74 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +19 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +31 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +28 ms] executing: C:\Users\Rahul Goti\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +56 ms] Exit code 0 from: C:\Users\Rahul Goti\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +19 ms] List of devices attached
[  +18 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +28 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +35 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +102 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.0\
[   +6 ms] Found plugin path_provider_fde at C:\Users\Rahul
Goti\Desktop\tiledmedia-1\plugins\flutter_plugins\path_provider_fde\
[  +37 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.3\
[ +139 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.0\
[   +4 ms] Found plugin path_provider_fde at C:\Users\Rahul
Goti\Desktop\tiledmedia-1\plugins\flutter_plugins\path_provider_fde\
[  +71 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.3\
[  +66 ms] Generating C:\Users\Rahul
Goti\Desktop\tiledmedia-1\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +127 ms] Launching lib\main.dart on Windows in debug mode...
[  +23 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest
-version 16 -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.Windows10SDK.17763
[ +141 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8
-latest -version 16 -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.Windows10SDK.17763
[   +2 ms] [
             {
               "instanceId": "78a8da02",
               "installDate": "2020-02-12T10:00:51Z",
               "installationName": "VisualStudio/16.4.5+29806.167",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise",
               "installationVersion": "16.4.29806.167",
               "productId": "Microsoft.VisualStudio.Product.Enterprise",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\2019\\Enterprise\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Enterprise 2019",
               "description": "Scalable, end-to-end solution for teams of any size",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.4.5",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2020-02-12T10:00:51.3697407Z",
               "catalog": {
                 "buildBranch": "d16.4",
                 "buildVersion": "16.4.29806.167",
                 "id": "VisualStudio/16.4.5+29806.167",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.4.5",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "5",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.4.5+29806.167",
                 "requiredEngineVersion": "2.4.1111.43337"
               },
               "properties": {
                 "campaignId": "522840778.1581490113",
                 "channelManifestId": "VisualStudio.16.Release/16.4.5+29806.167",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual
                 Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[  +18 ms] Building Windows application...
[  +27 ms] executing: [C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows/]
C:\flutter\packages\flutter_tools\bin\vs_build.bat C:\Program Files (x86)\Microsoft Visual
Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat Runner.sln Debug
[ +312 ms] **********************************************************************
[   +1 ms] ** Visual Studio 2019 Developer Command Prompt v16.4.5
[   +1 ms] ** Copyright (c) 2019 Microsoft Corporation
[   +1 ms] **********************************************************************
[+2682 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[ +301 ms] Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
[   +2 ms] Copyright (C) Microsoft Corporation. All rights reserved.
[        ] Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
[  +93 ms] Build started 15/02/2020 3:14:44 PM.
[ +219 ms] Project "C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\Runner.sln" on node 1 (default targets).
[   +9 ms] ValidateSolutionConfiguration:
[        ]   Building solution configuration "Debug|x64".
[ +349 ms] Project "C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\Runner.sln" (1) is building "C:\Users\Rahul
Goti\Desktop\tiledmedia-1\windows\Runner.vcxproj.metaproj" (2) on node 1 (default targets).
[   +1 ms] Project "C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\Runner.vcxproj.metaproj" (2) is building
"C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\FlutterBuild.vcxproj" (3) on node 1 (default targets).     
[   +1 ms] InitializeBuildStatus:
[        ]   Creating "x64\Debug\Flutter Build.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified. 
[  +78 ms] CustomBuildStep:
[        ]   Running Flutter backend build
[  +10 ms]   "C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\scripts\prepare_dependencies" Debug
[   +3 ms]   :VCEnd
[+14221 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "x64\Debug\Flutter Build.tlog\unsuccessfulbuild".
[        ]   Touching "x64\Debug\Flutter Build.tlog\Flutter Build.lastbuildstate".
[        ] Done Building Project "C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\FlutterBuild.vcxproj" (default       
targets).
[  +61 ms] Project "C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\Runner.vcxproj.metaproj" (2) is building
"C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\Runner.vcxproj" (4) on node 1 (default targets).
[  +48 ms] InitializeBuildStatus:
[   +2 ms]   Touching "C:\Users\Rahul
Goti\Desktop\tiledmedia-1\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild".       
[  +74 ms] ClCompile:
[  +41 ms]   C:\Program Files (x86)\Microsoft Visual
Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\CL.exe /c /ZI /JMC /nologo /W4 /WX /diagnostics:column 
/sdl /Od /D _MBCS /D _HAS_EXCEPTIONS=0 /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive-        
/Zc:wchar_t /Zc:forScope /Zc:inline /Fo"C:\Users\Rahul
Goti\Desktop\tiledmedia-1\windows\..\build\windows\intermediates\x64\Debug\Runner\\" /Fd"C:\Users\Rahul
Goti\Desktop\tiledmedia-1\windows\..\build\windows\intermediates\x64\Debug\Runner\vc142.pdb" /Gd /TP /wd4100 /FC        
/errorReport:queue main.cpp flutter\generated_plugin_registrant.cc
[ +133 ms]   main.cpp
[+1278 ms]   generated_plugin_registrant.cc
[ +278 ms] C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\flutter\generated_plugin_registrant.cc(7,10): fatal error
C1083: Cannot open include file: 'path_provider_plugin.h': No such file or directory [C:\Users\Rahul
Goti\Desktop\tiledmedia-1\windows\Runner.vcxproj]
[ +125 ms]   Generating Code...
[ +119 ms] Done Building Project "C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\Runner.vcxproj" (default targets) --
FAILED.
[   +2 ms] Done Building Project "C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\Runner.vcxproj.metaproj" (default
targets) -- FAILED.
[   +1 ms] Done Building Project "C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\Runner.sln" (default targets) --     
FAILED.
[ +165 ms] Build FAILED.
[   +3 ms] "C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\Runner.sln" (default target) (1) ->
[  +76 ms] "C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\Runner.vcxproj.metaproj" (default target) (2) ->
[        ] "C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\Runner.vcxproj" (default target) (4) ->
[        ] (ClCompile target) ->
[        ]   C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\flutter\generated_plugin_registrant.cc(7,10): fatal error 
C1083: Cannot open include file: 'path_provider_plugin.h': No such file or directory [C:\Users\Rahul
Goti\Desktop\tiledmedia-1\windows\Runner.vcxproj]
[   +1 ms]     0 Warning(s)
[        ]     1 Error(s)
[        ] Time Elapsed 00:00:17.08
[  +11 ms] Building Windows application... (completed in 20.7s)
[ +232 ms] "flutter run" took 22,158ms.
Build process failed. To view the stack trace, please run `flutter run -d windows -v`.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:77:5)
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#11     _rootRunUnary (dart:async/zone.dart:1134:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by stuartmorgan** [comment]
> C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\flutter\generated_plugin_registrant.cc(7,10): fatal error
C1083: Cannot open include file: 'path_provider_plugin.h': No such file or directory

Your project includes a plugin that you haven't correctly configured in the build system. Please provide:
- the output of `flutter doctor -v`, as was requested in the bug report template
- the exact steps you took to configure your Windows runner, including the hash of this repository you were using.

**Comment by gotirahul96** [comment]
> > C:\Users\Rahul Goti\Desktop\tiledmedia-1\windows\flutter\generated_plugin_registrant.cc(7,10): fatal error
> > C1083: Cannot open include file: 'path_provider_plugin.h': No such file or directory
> 
> Your project includes a plugin that you haven't correctly configured in the build system. Please provide:
> 
> * the output of `flutter doctor -v`, as was requested in the bug report template
> * the exact steps you took to configure your Windows runner, including the hash of this repository you were using.

The output of flutter doctor -v
[√] Flutter (Channel master, v1.15.4-pre.81, on Microsoft Windows [Version 10.0.18362.592], locale en-IN)
    • Flutter version 1.15.4-pre.81 at C:\flutter
    • Framework revision d3387bc916 (10 hours ago), 2020-02-14 21:51:47 -0800
    • Engine revision d60f298d9e
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 edd64e6d5c)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Rahul Goti\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.4.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.4.29806.167

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\Rahul Goti\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.18362.592]

! Doctor found issues in 1 category.

pubspec.yaml file :- 
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  path_provider: ^1.5.1
  path_provider_macos: ^0.0.2 # This can be removed once endorsed.
  path_provider_fde:
      path: plugins/flutter_plugins/path_provider_fde/

**Comment by stuartmorgan** [comment]
I still need the information I asked for in the second bullet point. When [you recreated your `windows` folder after updating Flutter](https://github.com/google/flutter-desktop-embedding/blob/master/example/README.md#copying-the-desktop-runners) what hash did you use as a source, and what steps did you take to integrate the plugin manually?

**Comment by gotirahul96** [comment]
> I still need the information I asked for in the second bullet point. When [you recreated your `windows` folder after updating Flutter](https://github.com/google/flutter-desktop-embedding/blob/master/example/README.md#copying-the-desktop-runners) what hash did you use as a source, and what steps did you take to integrate the plugin manually?

I used this Hash :- 82296566f18becd353205e51096441d8a69c2186 
and i just copy pasted the windows folder i saw that on a youtube video.

**Comment by stuartmorgan** [comment]
We have no control over what instructions people not associated with this project give; the only supported instructions are the official ones, which are in this repository.

Using plugins on Windows requires following [the plugin instructions](https://github.com/google/flutter-desktop-embedding/blob/master/plugins/README.md). Closing, as build failures are the expected outcome of not doing the manual steps at this point.

**Comment by gotirahul96** [comment]
> We have no control over what instructions people not associated with this project give; the only supported instructions are the official ones, which are in this repository.
> 
> Using plugins on Windows requires following [the plugin instructions](https://github.com/google/flutter-desktop-embedding/blob/master/plugins/README.md). Closing, as build failures are the expected outcome of not doing the manual steps at this point.

I'm sorry , I'm new to flutter.Thankyou for the help i followed the steps and was able to build,Thankyou.
