### ISSUE TITLE
Failed flutter run on macOS

### ISSUE THREAD

**Issue by shu11** [google/flutter-desktop-embedding#689]
I checked out the repo on mac, ran `flutter run -d macOS` in example/ and failed:
```shell
$ flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
** BUILD FAILED **


The following build commands failed:
        CopySwiftLibs /Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter\ Desktop\ Example.app
(1 failure)
Building macOS application...
Exception: Build process failed
```

verbose mode is the following:
```shell
[  +44 ms] CopySwiftLibs
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter\ Desktop\
Example.app (in target 'Runner' from project 'Runner')
[        ]     cd /Users/xxxxx/git/flutter/flutter-desktop-embedding/example/macos
[        ]     export CODESIGN_ALLOCATE=/usr/bin/codesign_allocate
[        ]     export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
[        ]     export
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
[        ]     builtin-swiftStdLibTool --copy --verbose --sign - --scan-executable
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter\ Desktop\
Example.app/Contents/MacOS/Flutter\ Desktop\ Example --scan-folder
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter\ Desktop\
Example.app/Contents/Frameworks --scan-folder
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter\ Desktop\
Example.app/Contents/PlugIns --scan-folder
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/macos/Flutter/ephemeral/App.framework
--scan-folder
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/macos/Flutter/ephemeral/FlutterMacOS.framework
--platform macosx --toolchain /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
--destination
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter\ Desktop\
Example.app/Contents/Frameworks --strip-bitcode --strip-bitcode-tool
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip
--emit-dependency-info
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Intermediates.noindex/Runner.bui
ld/Debug/Runner.build/SwiftStdLibToolInputDependencies.dep
[ +372 ms] libswiftDarwin.dylib is up to date at
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter Desktop
Example.app/Contents/Frameworks/libswiftDarwin.dylib
[  +12 ms] libswiftCore.dylib is up to date at
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter Desktop
Example.app/Contents/Frameworks/libswiftCore.dylib
[   +3 ms] libswiftObjectiveC.dylib is up to date at
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter Desktop
Example.app/Contents/Frameworks/libswiftObjectiveC.dylib
[        ] Probing signature of
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter Desktop
Example.app/Contents/Frameworks/libswiftDarwin.dylib
[        ] /usr/bin/codesign -r- --display
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter Desktop
Example.app/Contents/Frameworks/libswiftDarwin.dylib
[  +75 ms] Codesigning
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter Desktop
Example.app/Contents/Frameworks/libswiftDarwin.dylib
[        ] /usr/bin/codesign --force --sign - --verbose
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter Desktop
Example.app/Contents/Frameworks/libswiftDarwin.dylib
[+2616 ms]
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter Desktop
Example.app/Contents/Frameworks/libswiftDarwin.dylib: replacing existing signature
[        ]
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter Desktop
Example.app/Contents/Frameworks/libswiftDarwin.dylib: code failed to satisfy specified code requirement(s)
[        ] error: Failed with exit code 1 (in target 'Runner' from project 'Runner')
[  +13 ms] ** BUILD FAILED **
[   +4 ms] The following build commands failed:
[        ] 	CopySwiftLibs
/Users/xxxxx/git/flutter/flutter-desktop-embedding/example/build/macos/Build/Products/Debug/Flutter\ Desktop\
Example.app
[        ] (1 failure)
[  +78 ms] Building macOS application... (completed in 21.5s)
[  +17 ms] Exception: Build process failed
[   +4 ms] "flutter run" took 30,898ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:568:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:711:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:609:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1465:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:599:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1126:13)
#17     _CustomZone.run (dart:async/zone.dart:1023:19)
#18     _runZoned (dart:async/zone.dart:1518:10)
#19     runZoned (dart:async/zone.dart:1465:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#27     _rootRun (dart:async/zone.dart:1126:13)
#28     _CustomZone.run (dart:async/zone.dart:1023:19)
#29     _runZoned (dart:async/zone.dart:1518:10)
#30     runZoned (dart:async/zone.dart:1502:12)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#32     run.<anonymous closure> (package:flutter_tools/runner.dart)
#33     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:69:18)
<asynchronous suspension>
#34     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#36     _rootRun (dart:async/zone.dart:1126:13)
#37     _CustomZone.run (dart:async/zone.dart:1023:19)
#38     _runZoned (dart:async/zone.dart:1518:10)
#39     runZoned (dart:async/zone.dart:1465:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#41     runInContext (package:flutter_tools/src/context_runner.dart:72:24)
#42     run (package:flutter_tools/runner.dart:50:10)
<asynchronous suspension>
#43     main (package:flutter_tools/executable.dart:69:9)
#44     main (file:///Users/xxxxx/git/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

flutter run command failed at `CopySwiftLibs`, but the binary was generated in `build/macos/Build/Products/Debug` and could run.

I'm newbie for flutter. Please tell me what is matter.

**Comment by stuartmorgan** [comment]
The failure is in code signing of a standard macOS application build step; this isn't specific to Flutter.

I would suggest checking your code signing settings/certificates on the machine you are building on.

**Comment by shu11** [comment]
Thank you for your suggestion.
> I would suggest checking your code signing settings/certificates on the machine you are building on.

I've done settings for code sigining and be able to build as Debug build on xcode.

But `flutter run -d macOS` failed with above message.
