### ISSUE TITLE
[file_chooser] showOpenPanel fails with CO_E_NOTINITIALIZED on Windows

### ISSUE THREAD

**Issue by Eee721** [google/flutter-desktop-embedding#716]
It works well before upgrading the flutter sdk 1.18.0  

```
[√] Flutter (Channel master, v1.18.0-6.0.pre.19, on Microsoft Windows [Version 10.0.17134.1130], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.0)
[√] Android Studio (version 3.6)
[!] VS Code (version 1.40.2)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (4 available)
```

after upgrade, It failed.

 ```
file_chooser:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
```

```
[ERROR:c:\b\s\w\ir\cache\builder\src\flutter\lib\ui\ui_dart_state.cc(157)] Unhandled Exception: PlatformException(System error, Could not create dialog, -2147221008)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#3      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:342:40)
#4      FileChooserChannelController.show (package:file_chooser/src/channel_controller.dart:149:34)
#5      showOpenPanel (package:file_chooser/src/utilities.dart:42:8)
#6      FileUtils.pickImageFilePath (package:owl/utils/Common.dart:69:23)
```

**Comment by stuartmorgan** [comment]
> Could not create dialog, -2147221008

Looks like that's `0x800401F0`, which is `CO_E_NOTINITIALIZED`. It sounds like we used to be getting an initialize call from the Flutter library and aren't any more--probably it was a side-effect of something we were doing, since that wasn't a deliberate change.

It looks like this should probably be fixed in the template, initializing COM so that it's available for any plugin to use.

**Comment by 926** [comment]
you are my hero
