### ISSUE TITLE
windows build failed

### ISSUE THREAD

**Issue by Eee721** [google/flutter-desktop-embedding#734]
**Describe the bug**

build command:
flutter build windows -v

it failed.

```
[C:\projects\flutters\zendiao\windows\FlutterBuild.vcxproj]
[   +3 ms]     0 个警告
[        ]     3 个错误
[        ] 已用时间 00:00:00.95
[  +16 ms] Building Windows application... (completed in 2.1s)
[   +3 ms] "flutter windows" took 2,677ms.
Build process failed. To view the stack trace, please run `flutter run -d windows -v`.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:107:5)
#2      _rootRunUnary (dart:async/zone.dart:1198:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#11     _rootRunUnary (dart:async/zone.dart:1198:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Doctor Output**
Please provide the output of `flutter doctor -v`:
```
[√] Flutter (Channel master, 1.19.0-2.0.pre.83, on Microsoft Windows [Version 10.0.17134.1130], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.5)
[√] Android Studio (version 3.6)
[!] VS Code (version 1.40.2)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (3 available)

```

**Comment by stuartmorgan** [comment]
You haven't included the actual build error, which is earlier in the log output.

Also, which plugin or plugins from this repository did you add to your project that caused your build to start failing?

**Comment by stuartmorgan** [comment]
Closing due to lack of response.
