### ISSUE TITLE
window_size getWindowInfo error

### ISSUE THREAD

**Issue by 625859257** [google/flutter-desktop-embedding#798]
i have update window_size to the newest ,but when i getWindowInfo the package has error
like :
```
[ +133 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: Class 'bool' has no
instance method '[]'.
[   +2 ms] Receiver: true
[   +1 ms] Tried calling: []("frame")
[        ] #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
[        ] #1      WindowSizeChannel.getWindowInfo (package:window_size/src/window_size_channel.dart:140:53)
[        ] <asynchronous suspension>
[        ] #2      getWindowInfo (package:window_size/src/window_size_utils.dart:40:43)
[        ] #3      main (package:moon_jsq/main.dart:52:30)
[        ] #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
[        ] #5      _rootRun (dart:async/zone.dart:1190:13)
[        ] #6      _CustomZone.run (dart:async/zone.dart:1093:19)
[        ] #7      _runZoned (dart:async/zone.dart:1630:10)
[        ] #8      runZonedGuarded (dart:async/zone.dart:1618:12)
[        ] #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
[        ] #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
[        ] #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by stuartmorgan** [comment]
Please use the bug template when filing a bug; it's there for a reason. I need the `flutter doctor -v` output that was requested in the template before I can help.
