### ISSUE TITLE
Can't run the file_selector example on MacOS 10.14.6

### ISSUE THREAD

**Issue by Calin-Cosma** [google/flutter-desktop-embedding#823]
**Describe the bug**

I am trying to run the example on MacOS desktop and I can't. Below is the result of trying to run it from the console.

For the record, I created a new app (flutter create) and I can run it on MacOS.

```
$ flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                             897ms
CocoaPods' output:
↳

    [!] Invalid `Podfile` file: undefined local variable or method `flutter_macos_podfile_setup' for #<Pod::Podfile:0x00007f978a3b7170>
    Did you mean?  flutter_ios_podfile_setup.

     #  from /work/workspaces/samples/flutter-desktop-embedding/plugins/file_selector/example/macos/Podfile:27
     #  -------------------------------------------
     #  
     >  flutter_macos_podfile_setup
     #  
     #  -------------------------------------------

    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:318:in `rescue in block in from_ruby'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:312:in `block in from_ruby'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:50:in `initialize'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:310:in `new'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:310:in `from_ruby'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-core-1.10.0/lib/cocoapods-core/podfile.rb:276:in `from_file'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/config.rb:205:in `podfile'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:46:in `run'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/bin/pod:23:in `load'
    /usr/local/Cellar/cocoapods/1.10.0/libexec/bin/pod:23:in `<main>'

Exception: Error running pod install
```

**Doctor Output**
Please provide the output of `flutter doctor -v`:
```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Mac OS X 10.14.6 18G7016 darwin-x64, locale en-BE)
    • Flutter version 1.26.0-1.0.pre at /work/sdk/flutter
    • Framework revision 63062a6443 (4 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /work/sdk/android
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /work/sdk/android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.14.6 18G7016 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

**Comment by stuartmorgan** [comment]
>  Framework revision 63062a6443 (4 weeks ago), 2020-12-13 23:19:13 +0800

The example was created with a recent master; your version of Flutter is too old to build it. This project doesn't guarantee compatibility with anything but the latest master.

If you want to run the example with your version, you'll need to delete and recreate the `macos` folder (including re-adding the necessary entitlements).

**Comment by Calin-Cosma** [comment]
Flutter upgrade returns

```
$ flutter upgrade
Flutter is already up to date on channel dev
Flutter 1.26.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 63062a6443 (4 weeks ago) • 2020-12-13 23:19:13 +0800
Engine • revision 4797b06652
Tools • Dart 2.12.0 (build 2.12.0-141.0.dev)
```

I thought I was on the latest version.

What am I missing ?

**Comment by stuartmorgan** [comment]
You're on dev, not master.

Normally it wouldn't matter, but there happens to have been a project migration that landed after the last dev release, and this example was made after it landed.
