### ISSUE TITLE
Invalid kernel binary format with personal engine build

### ISSUE THREAD

**Issue by mikemaksymowych** [google/flutter-desktop-embedding#86]
When building the flutter engine from source, I have this issue trying to run the stock example:
```
MIKE formatVersion=7, kBinaryFormatVersion=8
[ERROR:flutter/runtime/dart_isolate.cc(710)] Can't load Kernel binary: Invalid kernel binary format version.
Segmentation fault (core dumped)
```
where the first log is added by me to debug the issue.

flutter-desktop-embedding: `080305c`
flutter: `5413560`
engine: `098a137`

I tried building the engine with the commit that `update_flutter_engine` pulls down, but no difference.

**Comment by mikemaksymowych** [comment]
In case this is relevant:
```
ubuntu@ubuntu:/tmp/kernel$ dart bin/dartk.dart flutter-desktop-embedding/example_flutter/build/flutter_assets/platform.dill 
Unhandled exception:
/home/ubuntu/flutter-src/flutter-desktop-embedding/example_flutter/build/flutter_assets/platform.dill:8: Invalid member reference tag: 7 at 
#0      BinaryBuilder.fail (package:kernel/binary/ast_from_binary.dart:46:5)
#1      BinaryBuilder.readMemberReference (package:kernel/binary/ast_from_binary.dart:264:15)
#2      BinaryBuilder.readProgramFile (package:kernel/binary/ast_from_binary.dart:189:22)
#3      BinaryLoader.loadProgram (package:kernel/binary/loader.dart:114:53)
#4      loadProgramFromBinary (package:kernel/kernel.dart:29:39)
#5      batchMain (file:///tmp/kernel/bin/dartk.dart:290:15)
<asynchronous suspension>
#6      main (file:///tmp/kernel/bin/dartk.dart:209:37)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by mikemaksymowych** [comment]
I forgot to run `gclient sync` after checking out the appropriate `engine.version`

shame on me :(
