### ISSUE TITLE
file_selector plugin is missing implementation on macOS

### ISSUE THREAD

**Issue by kakyoism** [google/flutter-desktop-embedding#863]
**Describe Request**

Seeing a few internet posts saying we could use `file_selector` plugin for letting users pick files/folders with the desktop builds of a flutter project. 

However, when I run the plugin example app on macOS, I got a lot of errors with every button on that app, e.g., when pressing `Save text into a file`, and giving all necessary info.

```sh
$ flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
Building macOS application...                                           
Syncing files to device macOS...                                    90ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:55251/PVJakZEgzB0=/
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9108?uri=http%3A%2F%2F127.0.0.1%3A55251%2FPVJakZEgzB0%3D%2F
2021-06-24 17:46:44.327 example[3230:55235308] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method getSavePath on channel plugins.flutter.io/file_selector)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      SaveTextPage._saveFile (package:example/save_text_page.dart:15:20)
<asynchronous suspension>

```
Is it that the desktop platforms are not supported yet?

**Comment by stuartmorgan** [comment]
See https://pub.dev/packages/file_selector_macos and/or https://github.com/google/flutter-desktop-embedding/blob/master/plugins/file_selector/README.md
